#!/usr/bin/env python3
"""
Compute the average number of words generated by each reasoning-level model.

This script reads:
    runs/reasoning_<N>/results.csv

For each level, it calculates:
    - Average word count of qwen_response
    - Median word count
    - Minimum and maximum word counts
    - Number of valid responses

Usage:
    python average_reasoning_words.py
"""

import csv
from pathlib import Path
from statistics import mean, median

RUNS_DIR = Path("runs")
REASONING_LEVELS = [1, 2, 3, 4, 5]


def word_count(text: str) -> int:
    """Count words in a string."""
    if not text:
        return 0
    return len(text.strip().split())


def analyze_level(level: int):
    csv_path = RUNS_DIR / f"reasoning_{level}" / "results.csv"

    if not csv_path.exists():
        print(f"reasoning_{level}: results.csv not found")
        return None

    counts = []

    with open(csv_path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)

        for row in reader:
            response = row.get("qwen_response", "").strip()

            # Skip invalid rows
            if response in {"", "SKIPPED"} or response.startswith("ERROR:"):
                continue

            counts.append(word_count(response))

    if not counts:
        print(f"reasoning_{level}: no valid responses")
        return None

    return {
        "level": level,
        "num_samples": len(counts),
        "average_words": mean(counts),
        "median_words": median(counts),
        "min_words": min(counts),
        "max_words": max(counts),
    }


def main():
    print("\n" + "=" * 80)
    print("AVERAGE RESPONSE LENGTH BY REASONING LEVEL")
    print("=" * 80)

    results = []

    for level in REASONING_LEVELS:
        stats = analyze_level(level)
        if stats:
            results.append(stats)

    if not results:
        print("No data found.")
        return

    header = (
        f"{'Level':<15}"
        f"{'Samples':>10}"
        f"{'Average':>15}"
        f"{'Median':>15}"
        f"{'Min':>10}"
        f"{'Max':>10}"
    )

    print(header)
    print("-" * len(header))

    for r in results:
        print(
            f"{'reasoning_' + str(r['level']):<15}"
            f"{r['num_samples']:>10}"
            f"{r['average_words']:>15.2f}"
            f"{r['median_words']:>15.2f}"
            f"{r['min_words']:>10}"
            f"{r['max_words']:>10}"
        )

    print("=" * 80)


if __name__ == "__main__":
    main()